name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get commit hash
        id: get-commit-hash
        run: echo "::set-output name=commit-hash::$(git rev-parse --short HEAD)"

      - name: Get timestamp
        id: get-timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y-%m-%d-%H-%M')"

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
          IMAGE_TAG: ${{ steps.get-commit-hash.outputs.commit-hash }}-${{ steps.get-timestamp.outputs.timestamp }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy:
    name: Deploy from ECR to EC2
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into EC2 and deploy latest image
        uses: appleboy/ssh-action@master
        with:
          host: ec2-3-86-102-151.compute-1.amazonaws.com
          username: ec2-user
          key: ${{ secrets.ACTIONS_PRIVATE_KEY }}
          envs: GITHUB_SHA ECR_REGISTRY ECR_REPOSITORY IMAGE_TAG
          script: |
            echo "Deployment started at $(date)"
            docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            docker stop your_container_name || true
            docker rm your_container_name || true
            docker run -d --restart always --name your_container_name -p 8080:80 $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            echo "Deployment completed at $(date)"
